version: "3.7"

services:
  client1:
    container_name: mpp-client1
    build:
      context: .
      dockerfile: docker/client1/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2201:22"
    networks:
      #mpp-internet:
      mpp-clients:
        ipv4_address: 172.30.10.2

  local:
    container_name: mpp-local
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2202:22"
    cap_add:
      - ALL
    networks:
      #mpp-internet:
      mpp-clients:
        ipv4_address: 172.30.10.3
      mpp-satl:
        ipv4_address: 172.30.20.2
      mpp-terl:
        ipv4_address: 172.30.30.2

  satcon:
    container_name: mpp-satcon
    build:
      context: .
      dockerfile: docker/satcon/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2203:22"
    networks:
      mpp-satl:
        ipv4_address: 172.30.20.3
      mpp-satr:
        ipv4_address: 172.30.21.2
      #mpp-internet:
    cap_add:
      - ALL

  tercon:
    container_name: mpp-tercon
    build:
      context: .
      dockerfile: docker/tercon/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2204:22"
    networks:
      mpp-terl:
        ipv4_address: 172.30.30.3
      mpp-terr:
        ipv4_address: 172.30.31.2
      #mpp-internet:
    cap_add:
      - ALL

  remote:
    container_name: mpp-remote
    build:
      context: .
      dockerfile: docker/remote/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2205:22"
    cap_add:
      - ALL
    networks:
      mpp-servers:
        ipv4_address: 172.30.40.2
      mpp-satr:
        ipv4_address: 172.30.21.3
      mpp-terr:
        ipv4_address: 172.30.31.3
      #mpp-internet:

  server1:
    container_name: mpp-server1
    build:
      context: .
      dockerfile: docker/server1/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2206:22"
    cap_add:
      - ALL
    networks:
      mpp-servers:
        ipv4_address: 172.30.40.3
      mpp-internet:

networks:
  mpp-internet:
    driver_opts:
      com.docker.network.bridge.name: internet
      com.docker.network.container_iface_prefix: internet
    ipam:
      config:
        - subnet: 172.30.254.0/24

  mpp-clients:
    driver_opts:
      com.docker.network.bridge.name: clients
      com.docker.network.container_iface_prefix: clients
    ipam:
      config:
        - subnet: 172.30.10.0/24

  mpp-satl:
    driver_opts:
      com.docker.network.bridge.name: satl
      com.docker.network.container_iface_prefix: satl
    ipam:
      config:
        - subnet: 172.30.20.0/24

  mpp-satr:
    driver_opts:
      com.docker.network.bridge.name: satr
      com.docker.network.container_iface_prefix: satr
    ipam:
      config:
        - subnet: 172.30.21.0/24

  mpp-terl:
    driver_opts:
      com.docker.network.bridge.name: terl
      com.docker.network.container_iface_prefix: terl
    ipam:
      config:
        - subnet: 172.30.30.0/24

  mpp-terr:
    driver_opts:
      com.docker.network.bridge.name: terr
      com.docker.network.container_iface_prefix: terr
    ipam:
      config:
        - subnet: 172.30.31.0/24

  mpp-servers:
    driver_opts:
      com.docker.network.bridge.name: servers
      com.docker.network.container_iface_prefix: servers
    ipam:
      config:
        - subnet: 172.30.40.0/24
