version: "3.9"

services:
#  client1:
#    container_name: client1
#    build:
#      context: .
#      dockerfile: docker/client1/Dockerfile
#    tty: true
#    privileged: true
#    ports:
#      - "2201:22"
#    networks:
#      internet:
#      clients:
#        ipv4_address: 172.30.10.1

#  local:
#    container_name: local
#    build:
#      context: .
#      dockerfile: docker/local/Dockerfile
#    tty: true
#    privileged: true
#    ports:
#      - "2202:22"
#    cap_add:
#      - ALL
#    networks:
#      internet:
#      clients:
#        ipv4_address: 172.30.10.2
#      satl:
#        ipv4_address: 172.30.20.1
#      terl:
#        ipv4_address: 172.30.30.1

  satcon:
    container_name: satcon
    build:
      context: .
      dockerfile: docker/satcon/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2203:22"
    networks:
      satl:
        ipv4_address: 172.30.20.2
      satr:
        ipv4_address: 172.30.21.1
      internet:
    cap_add:
      - ALL

#  tercon:
#    container_name: tercon
#    build:
#      context: .
#      dockerfile: docker/tercon/Dockerfile
#    tty: true
#    privileged: true
#    ports:
#      - "2204:22"
#    networks:
#      terl:
#        ipv4_address: 172.30.30.2
#      terr:
#        ipv4_address: 172.30.31.1
#      internet:
#    cap_add:
#      - ALL

#  remote:
#    container_name: remote
#    build:
#      context: .
#      dockerfile: docker/remote/Dockerfile
#    tty: true
#    privileged: true
#    ports:
#      - "2205:22"
#    cap_add:
#      - ALL
#    networks:
#      servers:
#        ipv4_address: 172.30.40.1
#      satr:
#        ipv4_address: 172.30.21.2
#      terr:
#        ipv4_address: 172.30.31.2
#      internet:

  server1:
    container_name: server1
    build:
      context: .
      dockerfile: docker/server1/Dockerfile
    tty: true
    privileged: true
    ports:
      - "2206:22"
    cap_add:
      - ALL
    networks:
      servers:
        ipv4_address: 172.30.40.2
      internet:

networks:
  internet:
    name: internet
    driver_opts:
      com.docker.network.bridge.name: internet
      com.docker.network.container_iface_prefix: internet
    ipam:
      config:
        - subnet: 172.30.254.0/24
          gateway: 172.30.254.254

  clients:
    name: clients
    driver_opts:
      com.docker.network.bridge.name: clients
      com.docker.network.container_iface_prefix: clients
    ipam:
      config:
        - subnet: 172.30.10.0/24
          #gateway: 172.30.10.254

  satl:
    name: satl
    driver_opts:
      com.docker.network.bridge.name: satl
      com.docker.network.container_iface_prefix: satl
    ipam:
      config:
        - subnet: 172.30.20.0/24
          #gateway: 172.30.20.254

  satr:
    name: satr
    driver_opts:
      com.docker.network.bridge.name: satr
      com.docker.network.container_iface_prefix: satr
    ipam:
      config:
        - subnet: 172.30.21.0/24
          #gateway: 172.30.21.254

  terl:
    name: terl
    driver_opts:
      com.docker.network.bridge.name: terl
      com.docker.network.container_iface_prefix: terl
    ipam:
      config:
        - subnet: 172.30.30.0/24
          #gateway: 172.30.30.254

  terr:
    name: terr
    driver_opts:
      com.docker.network.bridge.name: terr
      com.docker.network.container_iface_prefix: terr
    ipam:
      config:
        - subnet: 172.30.31.0/24
          #gateway: 172.30.31.254

  servers:
    name: servers
    driver_opts:
      com.docker.network.bridge.name: servers
      com.docker.network.container_iface_prefix: servers
    ipam:
      config:
        - subnet: 172.30.40.0/24
          #gateway: 172.30.40.254
