version: "3.9"

services:
  client1:
    image: mppnode
    build: .
    tty: true
    ports:
      - "2201:22"
    networks:
      clients:
        ipv4_address: 192.168.1.2

  left:
    image: mppnode
    build: .
    tty: true
    ports:
      - "2202:22"
    networks:
      clients:
        ipv4_address: 192.168.1.1
      ter:
        ipv4_address: 192.168.2.2
      sat:
        ipv4_address: 192.168.3.2

  right:
    image: mppnode
    build: .
    tty: true
    ports:
      - "2203:22"
    networks:
      servers:
        ipv4_address: 192.168.4.1
      ter:
        ipv4_address: 192.168.2.1
      sat:
        ipv4_address: 192.168.3.1

  server1:
    image: mppnode
    build: .
    tty: true
    ports:
      - "2204:22"
    networks:
      servers:
        ipv4_address: 192.168.4.2

networks:
  clients:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254

  ter:
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254

  sat:
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.254

  servers:
    ipam:
      config:
        - subnet: 192.168.4.0/24
          gateway: 192.168.4.254